
stages:
  - package
  - deploy

# 64-bit linux portable builds
package-linux-amd64:
  stage: package
  tags:
    - linux
  script:
    - release/ci-package.js linux amd64
  artifacts:
    expire_in: 1 week
    paths:
      - packages

# macOS .zip
package-darwin-amd64:
  stage: package
  tags:
    - darwin
  script:
    - release/ci-package.js darwin amd64
  artifacts:
    expire_in: 1 week
    paths:
      - packages

# windows 32-bit build
package-windows-386:
  stage: package
  retry: 2
  tags:
    - windows
  script:
    - release/ci-package.js windows 386
  artifacts:
    expire_in: 1 week
    paths:
      - packages

# windows 64-bit build
package-windows-amd64:
  stage: package
  retry: 2
  tags:
    - windows
  script:
    - release/ci-package.js windows amd64
  artifacts:
    expire_in: 1 week
    paths:
      - packages

deploy-itchio:
  stage: deploy
  when: manual
  tags:
    - linux
  only:
    - tags
  script:
    - release/ci-deploy.js
  dependencies:
    - package-linux-amd64
    - package-darwin-amd64
    - package-windows-386
    - package-windows-amd64
  
