
stages:
  - build # tsc, node-sass etc.
  - package # .rpm, .deb, .dmg., .zip
  - deploy # github releases, bintray, AUR

# Gitbook documentation
book:
  stage: build
  tags:
    - dropsy
  script:
    - release/ci-book.js

# Unit tests
test:
  stage: build
  tags:
    - linux
  script:
    - release/ci-test.js
  except:
    - tags

# JavaScript standard formatting
lint:
  stage: build
  tags:
    - linux
  script:
    - release/ci-lint.js
  except:
    - tags

# compile javascript & scss using babel & node-sass
compile:
  stage: build
  tags:
    - linux
  script:
    - release/ci-compile.js
  only:
    - tags
  artifacts:
    paths:
      - stage.tar.gz

# generate .desktop file for Linux
generate-linux-extras:
  stage: build
  tags:
    - linux
  script:
    - release/ci-generate-linux-extras.js
  only:
    - tags
  artifacts:
    paths:
      - linux-extras

# .tar.gz, .rpm and .deb
package-linux-386:
  stage: package
  tags:
    - linux
  script:
    - release/ci-package.js linux 386
  only:
    - tags
  artifacts:
    paths:
      - packages
  dependencies:
    - compile
    - generate-linux-extras

# .tar.gz, .rpm and .deb
package-linux-amd64:
  stage: package
  tags:
    - linux
  script:
    - release/ci-package.js linux amd64
  only:
    - tags
  artifacts:
    paths:
      - packages
  dependencies:
    - compile
    - generate-linux-extras

# .dmg and .zip
package-darwin-amd64:
  stage: package
  tags:
    - darwin
  script:
    - release/ci-package.js darwin amd64
  only:
    - tags
  artifacts:
    paths:
      - packages
  dependencies:
    - compile

package-windows-386:
  stage: package
  tags:
    - windows
  only:
    - tags
  script:
    - release/ci-package.js windows 386
  artifacts:
    paths:
      - packages
  dependencies:
    - compile

# ArchLinux user repository
package-aur:
  stage: package
  tags:
    - archlinux
  only:
    - tags
  script:
    - release/ci-package-aur.js

# GitHub releases are used for Squirrel.Windows & Squirrel.Mac,
# along with direct downloads
deploy-github:
  stage: deploy
  tags:
    - linux
  only:
    - tags
  script:
    - release/ci-deploy-github.js
  dependencies:
    - package-linux-386
    - package-linux-amd64
    - package-windows-386
    - package-darwin-amd64

# We have a YUM (rpm) & APT (deb) repository on bintray
deploy-bintray:
  stage: deploy
  tags:
    - linux
  only:
    - tags
  script:
    - release/ci-deploy-bintray.js
  dependencies:
    - package-linux-386
    - package-linux-amd64

