
stages:
  - package
  - deploy

# 64-bit linux portable builds
package-linux-amd64:
  stage: package
  tags:
    - linux
  script:
    - npm ci
    - node release/ci-package-all.js --os linux --arch amd64
  artifacts:
    expire_in: 1 week
    paths:
      - packages

# macOS .zip
package-darwin-amd64:
  stage: package
  tags:
    - darwin
  script:
    - npm ci
    - node release/ci-package-all.js --os darwin --arch amd64
  artifacts:
    expire_in: 1 week
    paths:
      - packages

# windows 32-bit build
package-windows-386:
  stage: package
  tags:
    - windows
  script:
    - npm ci
    - node release/ci-package-all.js --os windows --arch 386
  artifacts:
    expire_in: 1 week
    paths:
      - packages

# windows 64-bit build
package-windows-amd64:
  stage: package
  tags:
    - windows
  script:
    - npm ci
    - node release/ci-package-all.js --os windows --arch amd64
  artifacts:
    expire_in: 1 week
    paths:
      - packages

deploy-itchio:
  stage: deploy
  when: manual
  tags:
    - linux
  only:
    - tags
  script:
    - node release/ci-deploy.js
  dependencies:
    - package-linux-amd64
    - package-darwin-amd64
    - package-windows-386
    - package-windows-amd64
  
